import json
import argparse


def recalculate_metrics_by_deficiency(input_file: str, output_file: str = None):
    """
    Reads a JSON results file and recalculates metrics based on specific deficiencies
    instead of broad categories.

    Args:
        input_file (str): Path to the input JSON file from the previous evaluation.
        output_file (str, optional): Path to save the new metrics. Defaults to None.
    """
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            results_data = json.load(f)
        print(f"Successfully loaded results from: {input_file}")
    except FileNotFoundError:
        print(f"Error: The file '{input_file}' was not found.")
        return
    except json.JSONDecodeError:
        print(f"Error: The file '{input_file}' is not a valid JSON file.")
        return

    detailed_results = results_data.get("detailed_results")
    if not detailed_results:
        print("Error: 'detailed_results' key not found in the JSON file.")
        return

    # --- Initialization for new calculations ---
    total_tp = 0
    total_fp = 0
    total_fn = 0

    per_sample_precisions = []
    per_sample_recalls = []
    per_sample_f1s = []

    # --- Recalculate metrics for each sample ---
    for item in detailed_results:
        # Use the specific deficiency lists directly
        ground_truth_set = set(item.get("ground_truth_deficiencies", []))
        predicted_set = set(item.get("predicted_deficiencies", []))

        # Calculate TP, FP, FN for this specific sample
        tp = len(ground_truth_set.intersection(predicted_set))
        fp = len(predicted_set - ground_truth_set)
        fn = len(ground_truth_set - predicted_set)

        # Calculate metrics for this sample
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

        # Store for calculating average (macro) metrics
        per_sample_precisions.append(precision)
        per_sample_recalls.append(recall)
        per_sample_f1s.append(f1)

        # Accumulate for calculating overall (micro) metrics
        total_tp += tp
        total_fp += fp
        total_fn += fn

    # --- Calculate Final Metrics ---
    num_samples = len(detailed_results)

    # Average (Macro) Metrics: Average of each sample's score
    avg_precision = sum(per_sample_precisions) / num_samples if num_samples > 0 else 0
    avg_recall = sum(per_sample_recalls) / num_samples if num_samples > 0 else 0
    avg_f1 = sum(per_sample_f1s) / num_samples if num_samples > 0 else 0

    # Overall (Micro) Metrics: Calculated from the grand total of TP, FP, FN
    overall_precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) > 0 else 0
    overall_recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) > 0 else 0
    overall_f1 = (2 * overall_precision * overall_recall) / (overall_precision + overall_recall) if (overall_precision + overall_recall) > 0 else 0

    # --- Prepare Final Output ---
    new_metrics = {
        "calculation_level": "Specific Deficiency",
        "average_precision": avg_precision,
        "average_recall": avg_recall,
        "average_f1": avg_f1,
        "overall_precision": overall_precision,
        "overall_recall": overall_recall,
        "overall_f1": overall_f1,
        "total_true_positives": total_tp,
        "total_false_positives": total_fp,
        "total_false_negatives": total_fn
    }

    final_output = {
        "original_file": input_file,
        "total_samples_recalculated": num_samples,
        "recalculated_metrics": new_metrics
    }

    # --- Print and Save Results ---
    print("\n" + "="*50)
    print("=== Results Summary (Calculated by Specific Deficiency) ===")
    print(f"Total samples processed: {num_samples}")
    print(f"Average Precision: {avg_precision:.4f}")
    print(f"Average Recall: {avg_recall:.4f}")
    print(f"Average F1: {avg_f1:.4f}")
    print("-" * 20)
    print(f"Overall Precision: {overall_precision:.4f}")
    print(f"Overall Recall: {overall_recall:.4f}")
    print(f"Overall F1: {overall_f1:.4f}")
    print("="*50 + "\n")

    if output_file:
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(final_output, f, indent=4, ensure_ascii=False)
        print(f"Recalculated metrics saved to: {output_file}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Recalculate metrics from a deficiency test results file based on specific deficiencies."
    )
    parser.add_argument(
        "--input_file",
        type=str,
        default="deficiency_test_results_qwen-vl.json",
        help="Path to the JSON file generated by the evaluation script."
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="deficiency_test_results_qwen-vl_metrics.json",
        help="Path to save the newly calculated metrics. If not provided, results are only printed."
    )
    args = parser.parse_args()

    recalculate_metrics_by_deficiency(args.input_file, args.output_file)
